options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/spacelift-api-key/versions/latest
      env: 'SPACELIFT_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/spacelift-api-key-id/versions/latest
      env: 'SPACELIFT_API_KEY_ID'
    - versionName: projects/$PROJECT_ID/secrets/spacelift-stack-id/versions/latest
      env: 'SPACELIFT_STACK_ID'

substitutions:
  _SPACELIFT_API_URL: https://thoughtgears.app.spacelift.io/graphql

steps:
  - name: 'python'
    id: 'poll-spacelift-run'
    dir: resources/scripts
    entrypoint: 'python'
    args: [ '-m', 'pip', 'install', '-r', 'requirements.txt', '&&', 'poll_spacelift_run.py' ]
    env:
      - SPACELIFT_API_URL=$_SPACELIFT_API_URL
    secretEnv: [ 'SPACELIFT_API_KEY', 'SPACELIFT_API_KEY_ID', 'SPACELIFT_STACK_ID' ]

