options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/spacelift-api-key/versions/latest
      env: 'SPACELIFT_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/spacelift-api-key-id/versions/latest
      env: 'SPACELIFT_API_KEY_ID'
    - versionName: projects/$PROJECT_ID/secrets/spacelift-stack-id/versions/latest
      env: 'SPACELIFT_STACK_ID'

tags:
  - 'demo-services'

substitutions:
  _SPACELIFT_API_URL: https://thoughtgears.app.spacelift.io/graphql

steps:
  - name: 'gcr.io/$PROJECT_ID/spacelift'
    id: 'spacelift'
    args:
      - '--url=$_SPACELIFT_API_URL'
      - '--key-id=$$SPACELIFT_API_KEY_ID'
      - '--api-key=$$SPACELIFT_API_KEY'
      - '--stack-id=$$SPACELIFT_STACK_ID'
    secretEnv: [ 'SPACELIFT_API_KEY', 'SPACELIFT_API_KEY_ID', 'SPACELIFT_STACK_ID' ]