options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/spacelift-api-key/versions/latest
      env: 'SPACELIFT_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/spacelift-api-key-id/versions/latest
      env: 'SPACELIFT_API_KEY_ID'
    - versionName: projects/$PROJECT_ID/secrets/spacelift-stack-id/versions/latest
      env: 'SPACELIFT_STACK_ID'

substitutions:
  _SPACELIFT_API_URL: https://thoughtgears.app.spacelift.io/graphql
  _DOCKER_PLATFORM: $LOCATION-docker.pkg.dev/$PROJECT_ID/platform

steps:
  - name: '$_DOCKER_PLATFORM/poll-spacelift'
  - args:
      - '--spacelift-api-url=$_SPACELIFT_API_URL'
      - '----spacelift-api-key-id=$$SPACELIFT_API_KEY_ID'
      - '----spacelift-api-key=$$SPACELIFT_API_KEY'
      - '----spacelift-stack-id=$$SPACELIFT_STACK_ID'
    secretEnv: [ 'SPACELIFT_API_KEY', 'SPACELIFT_API_KEY_ID', 'SPACELIFT_STACK_ID' ]