options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/spacelift-api-key/versions/latest
      env: 'SPACELIFT_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/spacelift-api-key-id/versions/latest
      env: 'SPACELIFT_API_KEY_ID'
    - versionName: projects/$PROJECT_ID/secrets/spacelift-stack-id/versions/latest
      env: 'SPACELIFT_STACK_ID'

tags:
  - 'demo-services'

substitutions:
  _SPACELIFT_API_URL: https://thoughtgears.app.spacelift.io/graphql
  _SERVICE_NAME: 'backend'

steps:
  - name: 'gcr.io/$PROJECT_ID/spacelift'
    id: 'spacelift'
    args: [ '--url=$_SPACELIFT_API_URL', '--key-id=$$SPACELIFT_API_KEY_ID', '--api-key=$$SPACELIFT_API_KEY', '--stack-id=$$SPACELIFT_STACK_ID' ]
    secretEnv: [ 'SPACELIFT_API_KEY', 'SPACELIFT_API_KEY_ID', 'SPACELIFT_STACK_ID' ]

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [ 'spacelift' ]
    id: 'build'
    dir: services/$_SERVICE_NAME
    args: [ 'build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/demo/$_SERVICE_NAME:latest', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/platform/$_SERVICE_NAME:$SHORT_SHA', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [ 'build' ]
    id: 'push'
    args: [ 'push', '--all-tags', '$LOCATION-docker.pkg.dev/$PROJECT_ID/demo/$_SERVICE_NAME' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: [ 'push' ]
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image=$LOCATION-docker.pkg.dev/$PROJECT_ID/demos/$_SERVICE_NAME:$SHORT_SHA'
      - '--region=$LOCATION'
      - '--project=$PROJECT_ID'
      - '--no-allow-unauthenticated'
      - '--max-instances=1'
      - '--concurrency=80'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--service-account=run-$_SERVICE_NAME@$PROJECT_ID.iam.gserviceaccount.com'


