options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-poll-spacelift'
    dir: resources/cloud_build/poll_spacelift
    args:
      - 'build'
      - '-t'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/platform/poll-spacelift'
      - '.'

images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/platform/poll-spacelift'
tags:
  - 'cloud-build-builders'
  - 'v1'