options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-spacelift'
    dir: resources/cloud_build/spacelift
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/spacelift'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/spacelift'
tags:
  - 'cloud-build-builders'
  - 'v1'